Fix for inorder print in iterative style
arnaud-m/cryptator pull request #79
Opened 2022-12-09 17:26 UTC by FissoreD

The returned inorder expression only has usefull parenthesis are prented. 

❗ The formatter has moved the inner class TraversalEdge to the bottm of the class TreeTraversal.

2022-12-17 13:42 UTC, arnaud-m requested changes
Well done identifying the conditions for the minimal form. 
 
The difficulty with the iterative approach is to put the right/closing parenthesis.
Since it is not a critical code and the size of the tree will remain small, we **fall back to a recursive approach**. 

- Restore the previous `inorderTraversal` method.
- Specialize the `writeInorder` method. 
  - It does not call the `inorderTraversal`.
  - It rather performs its own recursive traversal. 
  - It has an option to trigger the minimal/full parenthesized form.    

Do not puth a space before or after a parenthesis.

2022-12-17 13:42 UTC, arnaud-m commented on src/main/java/cryptator/tree/TreeTraversals.java
> +    private static void buildDecoratedTree(final DecoratedTree decoratedNode){
First _recursive_ pass that decorates the tree.

2022-12-17 13:42 UTC, arnaud-m commented on src/main/java/cryptator/tree/TreeTraversals.java
>      public static void inorderTraversal(final ICryptaNode root, final ITraversalNodeConsumer traversalNodeConsumer) {
Second _iterative_ pass on the decorated tree.

2022-12-17 16:06 UTC, FissoreD commented
I've update the inorder print function as requested. 
The same function is overloaded and accepts a boolean for the full parenthesis mode.
The previous method inorder traversal has been restored as it was before my first modification.

2022-12-19 15:31 UTC, arnaud-m commented on src/main/java/cryptator/tree/TreeUtils.java
> +                                    final boolean allParenthesis){
Too many parameters.

2022-12-19 15:32 UTC, arnaud-m approved these changes

2022-12-20 16:41 UTC, merged